[IV-24-25] Objetivo_3
blancagiron/SeguraSenior pull request #19
Opened 2024-12-13 11:59 UTC by blancagiron

* [ ] ¿Incluye el fichero `iv.yaml` las claves de todos los objetivos
anteriores?
* [ ] ¿Se ha desarrollado el fichero para las tareas a partir de un
   issue?
* [ ] ¿Ese issue está asignado a un milestone?
* [ ] ¿El milestone incluye, entre sus productos mínimamente viables, la
  existencia de herramientas que permitan automatizar tareas?
* [ ] ¿Hemos justificado correctamente en caso de elegir un gestor de
   dependencias el que se use como gestor de tareas?
* [ ] ¿El PR, que también es un issue, está asignado al mismo milestone?
* [ ] ¿La tarea `check` efectivamente comprueba la sintaxis de los fuentes
  existentes y sólo eso?
* [ ] ¿Se ha comprobado que las instrucciones incluidas en el `README.md` son
completas y correctas?

2024-12-13 18:18 UTC, Carlosmapego8 requested changes
Buenas, se me ha asignado revisión en tu PR, te dejo algunos comentarios que te pueden servir de ayuda.

2024-12-13 18:18 UTC, Carlosmapego8 commented on iv.yaml
> +  fichero: Taskfile.yml
Deberías añadir el fichero que mencionas (Taskfile.yml) con la implementación del gestor de tareas.

2024-12-13 18:18 UTC, Carlosmapego8 commented on README.md
> +## Gestor de dependencias:
Creo que la justificación del gestor de dependencias quedaría más limpia como una documentación aparte enlazada desde este `README.md`. De la misma forma que lo has hecho con la justificación del gestor de tareas

2024-12-13 18:18 UTC, Carlosmapego8 commented on docs/gestor_tareas.md
> +Los criterios que se han seguido para escoger el gestor de tareas más adecuado son:
Si bien los criterios que has escogido son correctos, creo que son un poco escasos como justificación. Intenta incluir algunos más.

2024-12-13 19:30 UTC, blancagiron commented on iv.yaml
> +  fichero: Taskfile.yml
Hola, se me había pasado, acabo de añadirlo :)

2024-12-14 18:36 UTC, juanbarearojo commented on docs/gestor_tareas.md
> +- Facilidad de uso y familiaridad con el conocimiento. Se escogerá un gestor con el que se esté familiarizado con sus reglas y la sintaxis usada frente a uno del que se conozca menos.
Esto no es un criterio objetivo. La familiaridad es un concepto subjetivo.

2024-12-14 18:36 UTC, juanbarearojo commented on docs/gestor_tareas.md
> +Después de haber descartado Mage, Gilbert y Gotaskr por no cumplir con ninguno de los criterios, las opciones restantes son Make (ya que si bien no recibe actualizaciones constantes es una herramient
Si eliges Task debido a un criterio. Ese criterio debería verse reflejado en el documento

2024-12-14 18:36 UTC, juanbarearojo commented
En general veo trabajo realizado pero ten cuidado con establecer criterios subjetivos

2024-12-15 23:40 UTC, blancagiron commented on README.md
> +## Gestor de dependencias:
Hola, no creo que haga falta crear un archivo aparte porque go mod es el gestor de dependencias establecido de Go, no es algo que estemos eligiendo entre opciones. Cómo sólo explico qué es y cómo funciona, no lo justifico, creo que está bien incluirlo en el README.md para que sea información para quién consulte el proyecto. Creo que moverlo a otro archivo sería más lío.

2024-12-16 00:47 UTC, blancagiron commented on docs/gestor_tareas.md
> +Después de haber descartado Mage, Gilbert y Gotaskr por no cumplir con ninguno de los criterios, las opciones restantes son Make (ya que si bien no recibe actualizaciones constantes es una herramient
Lo añado en [255248d](https://github.com/blancagiron/SeguraSenior/pull/19/commits/255248d0e0aec1d8c7d9835ccdd93e5bef285cf6)

2024-12-16 00:48 UTC, blancagiron commented on docs/gestor_tareas.md
> +Los criterios que se han seguido para escoger el gestor de tareas más adecuado son:
He añadido más en [255248d](https://github.com/blancagiron/SeguraSenior/pull/19/commits/255248d0e0aec1d8c7d9835ccdd93e5bef285cf6)

2024-12-17 18:33 UTC, wickeet approved these changes
Tras los cambios que te comentaron mis compañeros y los cambios que has realizado, yo creo que el PR es correcto 👍

2024-12-17 18:56 UTC, blancagiron commented
@Carlosmapego8 @juanbarearojo  podríais echarle otro vistazo?? :)

2024-12-18 09:42 UTC, juanbarearojo reviewed
Un paso más cerca pero todavía quedan un par de cosas que retocar. En general intenta buscar cosas medibles, si son medibles suelen objetivas

2024-12-18 09:42 UTC, juanbarearojo commented on Taskfile.yml
> +      - "gofmt -e ./.."
¿Has probado esta orden a ejecutar?

2024-12-18 09:42 UTC, juanbarearojo commented on docs/gestor_tareas.md
> +- Comunidad y soporte: el gestor de tareas escogido debe contar con una comunidad activa, también en foros como Reddit o StackOverflow, para que la resolución de problemas sea más rápida, ya que cuan
¿Cual dirías que es la definición _documentación bien estructurada_? No crees que puede ser algo subjetivo

2024-12-18 14:57 UTC, blancagiron commented on docs/gestor_tareas.md
> +- Comunidad y soporte: el gestor de tareas escogido debe contar con una comunidad activa, también en foros como Reddit o StackOverflow, para que la resolución de problemas sea más rápida, ya que cuan
Lo cambio en [a4b2964](https://github.com/blancagiron/SeguraSenior/pull/19/commits/a4b29646c301bc160b289386b51e2cdc9a138495)

2024-12-18 15:26 UTC, blancagiron commented on docs/gestor_tareas.md
> +- Comunidad y soporte: el gestor de tareas escogido debe contar con una comunidad activa, también en foros como Reddit o StackOverflow, para que la resolución de problemas sea más rápida, ya que cuan
Bueno vuelvo a corregirlo en [a3f56af](https://github.com/blancagiron/SeguraSenior/pull/19/commits/a3f56af4c977aac5a1e2f96c84640858fe810f51)

2024-12-18 15:27 UTC, blancagiron commented on Taskfile.yml
> +      - "gofmt -e ./.."
Bueno vuelvo a corregirlo en [a3f56af](https://github.com/blancagiron/SeguraSenior/pull/19/commits/a3f56af4c977aac5a1e2f96c84640858fe810f51)

2024-12-18 16:07 UTC, blancagiron commented on docs/gestor_tareas.md
> +- Comunidad y soporte: el gestor de tareas escogido debe contar con una comunidad activa, también en foros como Reddit o StackOverflow, para que la resolución de problemas sea más rápida, ya que cuan
Evito los criterios vacíos en [a6fa92b](https://github.com/blancagiron/SeguraSenior/pull/19/commits/a6fa92b96ad25d635c51e1f14e4fdb03621bc056)

2024-12-18 18:03 UTC, juanbarearojo approved these changes

2024-12-18 18:37 UTC, blancagiron commented
@JJ revisión

2024-12-19 07:44 UTC, JJ requested changes
EStá en general aceptable; por favor mira estas dos o tres cosillas.

2024-12-19 07:44 UTC, JJ commented on README.md
> +## Gestor de dependencias:
Cerrad siempre con un commit, aquí o en otro lugar.

2024-12-19 07:44 UTC, JJ commented on docs/gestor_tareas.md
> +Debe haber actualizaciones regulares publicadas en los últimos 12 meses para considerar que la herramienta está activa y mantenida. El intervalo entre actualizaciones no debe ser superior a 3 meses y
Esto no es la frecuencia, es cuando se ha hecho la última actualización.

2024-12-19 07:44 UTC, JJ commented on docs/gestor_tareas.md
> +Debe tener una comunidad amplia y activa ya que una herramienta utilizada por un número significativo de usuarios suele ser un indicativo de su utilidad y estabilidad.
¿Esto lo puedes medir?

2024-12-19 07:44 UTC, JJ commented on docs/gestor_tareas.md
> +- Comunidad y soporte:
¿Por qué son lo mismo comunidad que soporte?

2024-12-19 07:44 UTC, JJ commented on docs/gestor_tareas.md
> +Después de haber descartado Mage, Gilbert y Gotaskr por no cumplir con ninguno de los criterios, descarto Make por no tener actualizaciones regulares frente a Just y Task que si las tienen. Las opcio
Si descartas make por no tener actualizaciones regulares no estás eligiendo una buena razón para elegir o no herramientas.

2024-12-19 08:02 UTC, blancagiron commented on docs/gestor_tareas.md
> +Después de haber descartado Mage, Gilbert y Gotaskr por no cumplir con ninguno de los criterios, descarto Make por no tener actualizaciones regulares frente a Just y Task que si las tienen. Las opcio
Lo corrijo aquí [2798470](https://github.com/blancagiron/SeguraSenior/pull/19/commits/279847002078a83120cea9e0edf00603e06c01ba)

2024-12-19 08:09 UTC, blancagiron commented on docs/gestor_tareas.md
> +Debe haber actualizaciones regulares publicadas en los últimos 12 meses para considerar que la herramienta está activa y mantenida. El intervalo entre actualizaciones no debe ser superior a 3 meses y
Corregido en [1b26706](https://github.com/blancagiron/SeguraSenior/pull/19/commits/1b26706ac86418ef7623eafba8d0d004ff614ad3)

2024-12-19 08:19 UTC, blancagiron commented on docs/gestor_tareas.md
> +Debe tener una comunidad amplia y activa ya que una herramienta utilizada por un número significativo de usuarios suele ser un indicativo de su utilidad y estabilidad.
corregido en [49fdf62](https://github.com/blancagiron/SeguraSenior/pull/19/commits/49fdf6259807727f85214f4a2c4b198e54b2a301)

2024-12-19 08:20 UTC, blancagiron commented on docs/gestor_tareas.md
> +- Comunidad y soporte:
Lo corrijo aquí [49fdf62](https://github.com/blancagiron/SeguraSenior/pull/19/commits/49fdf6259807727f85214f4a2c4b198e54b2a301)

2024-12-19 08:20 UTC, blancagiron commented
@JJ revisión

2024-12-19 08:28 UTC, blancagiron commented on docs/gestor_tareas.md
> +Debe haber actualizaciones regulares publicadas en los últimos 12 meses para considerar que la herramienta está activa y mantenida. El intervalo entre actualizaciones no debe ser superior a 3 meses y
Añado otro aspecto en [26e22f1](https://github.com/blancagiron/SeguraSenior/pull/19/commits/26e22f1fd89043bf73324af70f2db9f629e7f5ba)

2024-12-19 08:41 UTC, JJ reviewed
Te queda muy poquito, ánimo.

2024-12-19 08:41 UTC, JJ commented on docs/gestor_tareas.md
> +- **Mage:** Si bien su comunidad es grande, las actualizaciones de este gestor cuentan con largos períodos de inactividad en su desarrollo, esto causa dudas sobre si podría incrementar la deuda técni
No has dicho cuál es la última actualización.

2024-12-19 08:41 UTC, JJ commented on docs/gestor_tareas.md
> +- **Make:** Herramienta muy conocida y consolidada. No recibe actualizaciones desde hace un tiempo pero ya está establecida y cuenta con una gran comunidad. Su documentación se puede consultar en [es
Será que la madurez entonces es un criterio, aparte de los dichos, ¿no?

2024-12-19 08:41 UTC, JJ commented on docs/gestor_tareas.md
> +Debe haber actualizaciones regulares publicadas en los últimos 12 meses para considerar que la herramienta está activa y mantenida. El intervalo entre actualizaciones no debe ser superior a 3 meses y
Si un criterio no es necesario por algo, es que eso es otro criterio, ¿no?

2024-12-19 08:41 UTC, JJ commented on README.md
> +task test
¿Estamos haciendo test ahora mismo?

2024-12-19 08:41 UTC, JJ commented on iv.yaml
> +  fichero: Taskfile.yml
Por favor, resuelve *siempre* con un commit. Di el commit en el que lo has añadido y ya está.

2024-12-19 08:46 UTC, blancagiron commented on docs/gestor_tareas.md
> +Debe haber actualizaciones regulares publicadas en los últimos 12 meses para considerar que la herramienta está activa y mantenida. El intervalo entre actualizaciones no debe ser superior a 3 meses y
Corregido en [61dcfbd](https://github.com/blancagiron/SeguraSenior/pull/19/commits/61dcfbdf2e714e5a0d024cfaba06ee0c28bbf3a3)

2024-12-19 08:46 UTC, blancagiron commented on docs/gestor_tareas.md
> +- **Make:** Herramienta muy conocida y consolidada. No recibe actualizaciones desde hace un tiempo pero ya está establecida y cuenta con una gran comunidad. Su documentación se puede consultar en [es
corregido en [61dcfbd](https://github.com/blancagiron/SeguraSenior/pull/19/commits/61dcfbdf2e714e5a0d024cfaba06ee0c28bbf3a3)

2024-12-19 08:49 UTC, blancagiron commented on README.md
> +task test
corregido en [6852010](https://github.com/blancagiron/SeguraSenior/pull/19/commits/6852010cc40ed5833bd50f8689aa42e7f1c3364f) y en [552290c](https://github.com/blancagiron/SeguraSenior/pull/19/commits/552290c5d587b5634ce2de7be391133cefe6ba97)

2024-12-19 08:51 UTC, blancagiron commented on docs/gestor_tareas.md
> +- **Mage:** Si bien su comunidad es grande, las actualizaciones de este gestor cuentan con largos períodos de inactividad en su desarrollo, esto causa dudas sobre si podría incrementar la deuda técni
corregido en [80a6719](https://github.com/blancagiron/SeguraSenior/pull/19/commits/80a67190077438181980a3ff7a4facb279e335f4)

2024-12-19 08:51 UTC, blancagiron commented
@JJ revisión

2024-12-19 08:53 UTC, JJ approved these changes
Por favor, cierra las cosas solo una vez. El resto de las veces simplemente pon `#` issue y listo.

2024-12-19 12:05 UTC, evaanngiil requested changes
Buenas se me ha asignado revisar tu PR. Como bien te indica @JJ  estas por el buen camino. Te menciono algunos apuntes puntuales.

2024-12-19 12:05 UTC, evaanngiil commented on README.md
> +- [Gestor de dependencias](./docs/gestor_dependencias.md)
Te recomiendo añadir más detalles en el README, donde especifiques qué gestor de dependencias y tareas has elegido apoyándote en la documentación a la que haces referencia.

2024-12-19 12:05 UTC, evaanngiil commented on docs/gestor_tareas.md
> +Debe haber discusiones relacionadas con la herramienta en foros relevantes (por ejemplo, StackOverflow o Reddit). Esto se debe cumplir para que la resolución de problemas sea más rápida, ya que cuand
Un apunte menor, te recomiendo que en la parte de definición de criterios no mencionar directamente alguno de los gestores. Ya será en el propio gestor donde expliques su relación con el criterio y lo comparas con el resto.

2024-12-19 13:05 UTC, evaanngiil reviewed
Buenas de nuevo Blanca, no me he dado cuenta de que el profesor te ha aprobado el objetivo. Te dejo comentado un pequeño apunte para las siguientes prácticas.

2024-12-19 19:44 UTC, merged