[IV-24-25] Entrega Objetivo 1
blancagiron/SeguraSenior pull request #6
Opened 2024-10-10 06:54 UTC by blancagiron

# Sobre los milestones:
* [x] ¿Las historias de usuario y los milestones constituyen una guía
    suficiente para poder comenzar el desarrollo de un proyecto?
* [x] ¿Los milestones están ordenados correctamente, de forma que el 1 o
   0 sea lo primero que hay que empezar a publicar?
* [x] ¿Todos los milestones se construyen sobre el anterior, teniendo un
   orden lógico el desarrollo?
* [x] ¿El milestone 0 tiene asignada alguna historia de usuario?
* [x] ¿El milestone 0 corresponde con lo mencionado varias veces en
   clase, y en concreto con lo que se solicita en el objetivo
   siguiente?
* [x] ¿Todos los milestones describen correctamente un producto y qué
   lo hace válido, y no un  concepto vago, una funcionalidad o una tarea?
* [x] ¿Los milestones son graduales, o hay un salto grande entre ellos?
* [x] ¿Los milestones iniciales son internos, y hay a continuación milestones o
   productos externos?
* [x] ¿Los milestones son mínimos, es decir, incluyen un producto
   mínimamente viable para poder avanzar?
* [x] ¿El milestone 0 es mínimo *y* viable?
* [x] ¿Se indica claramente cómo comprobar la viabilidad del PMV de cada hito? Es
    decir, ¿se dice qué requisitos técnicos tiene que cumplir el producto de
    cada hito?
* [x] ¿Entre dos milestones consecutivos, no hay ningún PMV posible o por el
    contrario podrían desarrollarse muchas posibles etapas internas o externas
    de un proyecto?
---
# Sobre las historias de usuario:
* [x] ¿He tenido en cuenta en las historias de usuario que se trata de un
   proyecto que se desplegará en la nube?
* [x] ¿Están descritos todos los conceptos mencionados en las HUs con
   suficiente claridad, generalmente en documentos aparte?
* [x] ¿Tienen coherencia suficiente las historias de usuario, y en caso
   de que no lo tengan, se ha escrito un *user journey* para
   aclararlo?
* [x] ¿Todas las historias de usuario representan un beneficio para el
    mismo y se relacionan con la lógica de negocio? Es decir, ¿los usuarios
    *desean* hacerlo o tú deseas que el usuario te lo pida para hacerlo?

2024-10-10 09:25 UTC, wickeet commented on docs/milestones.md
> +## [M3] Implementación de filtros de búsqueda
Tanto el M3 como el M4 no serían sub-partes del M5? Me refiero, son características del sistema final y no sé seguro si tienen la fuerza suficiente para ser independientes. El M3 no dejaría de ser sentencias SQL más específicas (en el caso de que se usase SQL, si no otro lenguaje de consulta) y el M4 a no ser que tenga que ver algo con preprocesamiento las debería de generar directamente el sistema final cuando accede a la base de datos.

2024-10-10 11:25 UTC, juanbarearojo commented on .gitignore
> +
Entre la superación de un objetivo y otro. Se puede hacer cambios ciertos cambios al código. entre estos se incluye los cambios posibles al gitignore. Esto con el objetivo de que el revisor tenga una menor carga de trabajo.

2024-10-10 11:25 UTC, juanbarearojo commented on README.md
>  # SeguraSenior
Lo mismo con el READme.md Ciertos cambios como tipos sin corregir o cambios en la estructura del no es necesario incluirlos en el pr.

2024-10-10 11:25 UTC, juanbarearojo commented on docs/milestones.md
> +## [M1] Recopilación de conjunto de datos demográficos:
¿Has considerado integrar este milestone dentro del m2? La recolección de información se considera una tarea mas que un hito en el desarollo aun siendo necesario realizarlo not supone la con la suficiente importancia para que tenga un milestoen propio

2024-10-10 11:25 UTC, juanbarearojo commented on docs/milestones.md
> +## [M2] Integrado y estructurado de datos
Esto parecido al comentario anterior. Por lo que he visto gran parte de la lógica de negocio se encuentra en una combinacion del M3,M4,M5 ¿Has considerado  juntarlos en un único objetivo?

2024-10-10 11:27 UTC, juanbarearojo commented
Me han asignado corregir tu PR. Las historias de usuario y el user journey las veo bien. Pero milestone he puesto posible recomendaciones.

2024-10-11 09:26 UTC, blancagiron commented on docs/milestones.md
> +## [M3] Implementación de filtros de búsqueda
Tienes razón, al ser características que el sistema final necesita integrar sí o sí, tiene más sentido agruparlas en M5. Lo he corregido, gracias !

2024-10-11 09:54 UTC, blancagiron commented on docs/milestones.md
> +## [M2] Integrado y estructurado de datos
Sí, antes los había separado en milestones diferentes porque pensé que tenían que ser más graduales y creía que dividirlo así era lo más adecuado para el desarrollo. Tras revisarlo viendo las correcciones, es verdad que tiene más sentido juntar toda esa lógica de negocio en un único objetivo, ya que están muy conectados. Ya lo he corregido, gracias :)

2024-10-17 06:42 UTC, wickeet approved these changes

2024-10-17 06:46 UTC, blancagiron commented
@JJ revisión

2024-10-17 07:17 UTC, JJ reviewed
Hay que resolver todos los comentarios antes de pedir revisión.
En el caso del .gitignore habrá que modificarlo en main y hacer un rebase.

2024-10-17 07:28 UTC, blancagiron commented
@JJ ya he resuelto los comentarios y hecho el rebase, revisión.

2024-10-17 07:39 UTC, JJ commented on .gitignore
> +
Blanca, no está resuelta. El `.gitignore` sigue aquí.

2024-10-17 08:06 UTC, blancagiron commented
@JJ revisión

2024-10-21 05:48 UTC, JJ requested changes
Perdón, me había quedado esto pendiente.

2024-10-23 08:45 UTC, blancagiron commented
@JJ revisión

2024-10-23 08:56 UTC, JJ requested changes
Por favor, mira en [errores frecuentes](https://github.com/JJ/IV-/blob/master/errores/objetivo-1.md):

> Otro ejemplo es decir "hacer un modelo que incluya la clase a, b y la c". "Hacer un modelo" es precisamente saber cuales son esas clases y qué es lo que incluyen o cómo se comportan.

En resumen, hay que entender por qué hay que hacer un modelo del problema, y cómo hay que entregar ese modelo, porque sin esta información es imposible comenzar a trabajar con el objetivo 2 por parte de otra persona.

2024-10-23 08:56 UTC, JJ commented on docs/historias.md
> +Fran es concejal en un pequeño municipio de la Sierra de Segura. Preocupado por el envejecimiento de la población y la necesidad de obtener más recursos, necesita acceder a informes demográficos que
Por favor, trata de ser un poco más precisa. "Acceder" ya puede, no tiene más que descargárselos. Si lo que estás buscando aquí es un procesamiento específico, trata de explicar qué tipo de procesamiento necesita y justificarlo.
En las historias de usuario es esencial ser preciso, porque es lo que se va a usar para tratar de modelizar el problema. Por ejemplo, más recursos ¿para qué? ¿Estás diciendo que necesita calcular qué recursos va a necesitar?

2024-10-23 08:56 UTC, JJ commented on docs/journeys.md
> +Raquel trabaja en Madrid y necesita escribir un reportaje sobre la despoblación en la Sierra de Segura. Requiere datos demográficos detallados para completar su investigación.
Los UJ sirven para dos cosas
1. Aportar información adicional a las historias de usuario, en cuyo caso *deben enlazarse desde las mismas*. ¿Te parece que esto contenga algún contexto o información adicional?
2. Ayudarte a ti a crear una o varias HU entendiendo como se va a usar. ¿Te ha servido para algo?

En función de los dos anteriores, ¿crees que debes añadir o quitar algo de aquí?

2024-10-23 08:56 UTC, JJ commented on docs/journeys.md
> +1. **Identificación de la necesidad**: Raquel se da cuenta de que necesita datos específicos para su reportaje.
Lee el comentario de más arriba.

2024-10-23 08:56 UTC, JJ commented on docs/milestones.md
> +  Diseño e implementación de un modelo de entidades que represente los elementos demográficos clave de la Sierra de Segura (población, edades, migración, etc.). Este modelo será la base para almacena
¿Qué es un "modelo de entidades"?
Si ya sabes cuales son los elementos demográficos clave, aquí enumerados, ¿para qué quieres hacer el modelo?

2024-10-24 06:55 UTC, blancagiron commented
@JJ revisión

2024-10-24 09:40 UTC, JJ requested changes
Os rogaría que tomárais el enfoque de entender como se enmarcan los comentarios que se hacen dentro de la comprensión de un concepto, ajustar vuestro modelo de un concepto (como HU o PMV) y reescribir en el punto que se ha comentado reflejando esa nueva compresión. Si no, este ejercicio de evaluación formativa acaba limitándose a cambiar cosas de sitio o escribir más cosas, y no a una expresión de conceptos que se han entendido y se han intentado usar en la práctica.

2024-10-24 09:40 UTC, JJ commented on docs/historias.md
> +- Acceder y analizar datos demográficos detallados en un solo lugar.
Os rogaría que hiciérais un pequeño esfuerzo por entender lo que se pide y por qué, y no literalmente escribir lo que parece que se pide en una lectura superficial del comentario.

Yo *no* he dicho que los user journey haya que copiarlos aquí. Las HUs siguen siendo una expresión de los problemas de los usuarios y una división de esos problemas en partes abordables. ¿Te parece que "Acceder y analizar datos demográficos" encaje dentro de esa definición? Es más, ¿te parece que añadirlo aquí aporta algo a la persona que quiere desarrollar basada en esta historia de usuario?

2024-10-24 10:01 UTC, JJ requested changes
Fuera de los detalles específicos, que puedo comentar o no pero que en realidad parece que sirven de poco, puesto que no tratáis de responder específicamente a los comentarios elaborando un modelo conceptual diferente y reflejándolo, lo que quizás debería pedir aquí es un cambio, pero de actitud. Los conceptos a este nivel son relaivamente simples, y realmente cuesta menos trabajo tratar de entender qué es y para qué sirve una historia de usuario o un producto mínimamente viable y reflejarlo en la práctica que hacer infinitas iteraciones de texto escrito (con ayuda de IA o no). Te rogaría que consideraras esa forma de trabajar, porque realmente estás capacitada para ello y al final se reflejará en una serie de aptitudes (pero sobre todo, actitudes) que te permitirán acceder a empleos mejores y a desempeñarte en ellos con eficiencia.

2024-10-24 10:16 UTC, blancagiron commented on docs/historias.md
> +Fran es concejal en un pequeño municipio de la Sierra de Segura. Preocupado por el envejecimiento de la población y la necesidad de obtener más recursos, necesita acceder a informes demográficos que
Hola profesor, los cambios de HU han sido correspondientes a este comentario. Vi que la ,HU de Fran no estaba bien hecha y creí que había cometido los mismos errores en Raquel. Los títulos genéricos en los commit se deben a que he hecho pequeños cambios por ejemplo refiriéndome al título de los PMV porque creía que los títulos debían ser productos y no actividades y lo había corregido. Por otro lado el cambio de formato de las UJ se debe a que no comprendí bien que corrección me hizo y pedí consejo a mis compañeros para saber qué podía hacer, de hecho iba a quitar las UJ porque ya había hecho las HU, después de hablar con mis compañeros consideré que comprendía mejor el nuevo formato. No he hecho uso de una IA generativa, y si he hecho actualizaciones en cosas sobre las que no se ha hecho comentario ha sido un error involuntario.

2024-10-24 11:30 UTC, blancagiron commented
@JJ revisión

2024-10-24 11:48 UTC, JJ requested changes
Por favor, dale una vuelta que ya casi está 👍

2024-10-24 11:48 UTC, JJ commented on docs/milestones.md
> +	Código que implementa un modelo de entidades clave de la Sierra de Segura. El código debe permitir definir las relaciones entre las entidades, como la relación entre un municipio y su población, ase
Por favor, hablad siempre explícitamente de las historias de usuario con las que estéis trabajando. Incluso aunque sea una, no cuesta ningún trabajo mencionarla (además, en ágil pueden añadirse HUs en cualquier momento)

2024-10-24 11:48 UTC, JJ commented on docs/milestones.md
> +  Código que crea la base de datos estructurada según el modelo de entidades definido e implementado en el milestone anterior. Se recopilarán y almacenarán datos demográficos reales de la Sierra de S
Si se especifica en concreto la solución, no se da lugar a que la persona que desarrolle tome sus decisiones basadas en la HU.

2024-10-24 11:48 UTC, JJ commented on docs/milestones.md
> + El sistema será viable cuando: se puedan realizar consultas filtradas sobre los datos demográficos, como segmentar la población por rangos de edad y localidades específicas, los usuarios puedan visu
Tampoco puedes mencionar soluciones específicas. En este milestone que se implementa la lógica de negocio, está clara cual es la viabilidad: que efectivamente se puedan resolver problemas indicados en la hU, ¿no te parece?

2024-10-25 10:35 UTC, merged