closes blancagiron#7
blancagiron/SeguraSenior pull request #8
Opened 2024-11-03 01:04 UTC by ChinChainis

creado archivo iv.yaml que contiene lenguaje y entidad

2024-11-17 23:06 UTC, ChinChainis commented
@blancagiron si pudieras echarle un ojo, gracias

2024-11-18 09:44 UTC, blancagiron commented
* [ ] ¿Los issues que ha planteado la persona son efectivamente problemas y
evidencian comprensión de las historias de usuario? Si no es así, es mejor que
se le transmita antes de que empiece a crear cualquier código erróneo.
* [ ] ¿Has comprobado que efectivamente el compañero/a ha seguido *su* lista de
      comprobación?
* [ ] ¿El código creado es una modelización válida de las historias de usuario
      creadas por ti, y te sirve como base para programar la lógica de negocio?
* [ ] ¿El código creado sigue las mejores prácticas para el lenguaje de
      programación que hayáis consensuado, tanto en identificadores, como
      nombres de ficheros, como disposición de los diferentes ficheros en el
      repositorio? Por ejemplo, ¿todos los commits se refieren a un issue y
      aportan código para resolver el problema planteado en el mismo?
* [ ] ¿He comprobado que el código compile, o que quien lo ha programado ha lo
ha hecho y documentado en el repositorio?
* [ ] ¿He añadido el PR y todos los issues que se resuelvan en él al milestone
correspondiente, que será el primero?
* [ ] ¿Cubre totalmente el milestone 0, o hará falta modelización adicional en
el objetivo 4 para poder programar la lógica de negocio?
* [ ] En resumen, ¿considero que con lo hecho puedo ponerme a trabajar
directamente en el siguiente milestone, que incluye la lógica de negocio?

2024-11-18 10:45 UTC, blancagiron commented
He revisado el trabajo y, en general, me parece bien enfocado. Sin embargo, creo que hay algunas cosas que podrían mejorarse para que el modelado sea más completo y se ajuste mejor a la historia de usuario, aunque entiendo que cada enfoque tiene sus propias decisiones.

- En #2 se menciona el problema del formato y creo que en este modelado no se ha visto representado, además considero que en este punto la función de contrastar fuentes no es necesaria.
- En el constructor de reportaje.go el parámetro orig no se ha usado.
- Creo que el modelo se centra en la entidad Reportaje, lo que refleja solo el producto final (la investigación periodística), dejando fuera las etapas previas de procesamiento y estructuración de los datos demográficos.
- Según como he entendido la propuesta, la ausencia de una entidad que represente las poblaciones individuales complica la tarea de #2 de consultar, organizar y analizar los datos específicos por población.
- En lo que respecta a mejorar las prácticas de Go, el uso de /src creo que ya no es una práctica recomendada, por lo que he leído es mejor usar una estructura de directorios basada en paquetes.



Si necesitas ayuda o quieres comentar alguna parte en detalle,  estaré encantada de echar una mano. ¡Ánimo con el proyecto!

2024-11-21 08:04 UTC, blancagiron commented
Hola, tras revisar los cambios que se han hecho y ver que se han tenido en cuenta las indicaciones que he dicho, yo lo veo bien y creo que está listo para ser revisado por el profesor. Voy a cambiarle el nombre al PR porque si no creo que va a dar error.

2024-11-21 08:10 UTC, ChinChainis commented
Gracias Blanca, @JJ podrías revisarlo?

2024-11-21 08:33 UTC, JJ commented
@blancagiron tienes que aprobar dándole a "Approve" e incluyendo la lista de comprobación.

2024-11-21 08:37 UTC, JJ commented on pkg/segurasenior/reportaje.go
> +func AniadirRepo(nom string, pobla int, medio string, orig []Fuente) *Reportaje {
¿Un modelo tiene funciones?

2024-11-21 08:37 UTC, JJ commented on pkg/segurasenior/reportaje.go
> +	Retransmision string
¿Esto es relevante para la lógica de negocio?

2024-11-21 08:42 UTC, JJ commented on pkg/segurasenior/poblacion.go
> +	Tasanat        int //medido en tantos por mil
Los nombres son importantes. Las abreviaturas se deben evitar. Y deben seguir la convención del lenguaje.

2024-11-21 09:00 UTC, ChinChainis commented on pkg/segurasenior/poblacion.go
> +	Tasanat        int //medido en tantos por mil
https://github.com/blancagiron/SeguraSenior/commit/26d335be7189050d0062f5efa6ad36369f5ff3a3

2024-11-21 12:02 UTC, ChinChainis commented on pkg/segurasenior/reportaje.go
> +func AniadirRepo(nom string, pobla int, medio string, orig []Fuente) *Reportaje {
https://github.com/blancagiron/SeguraSenior/pull/8/commits/df1308b3355a4a8359f05e4afc50c72e3adec2b2

2024-11-21 12:03 UTC, ChinChainis commented on pkg/segurasenior/reportaje.go
> +	Retransmision string
No lo es, es cierto.

2024-11-21 12:05 UTC, ChinChainis commented
@JJ listo para revisión

2024-11-21 13:23 UTC, JJ commented
@blancagiron por favor, revisa y aprueba explícitamente pulsando en "Review"

2024-11-21 13:37 UTC, blancagiron approved these changes
Perdón por no aprobarlo antes, tras revisarlo yo lo veo bien. Una sugerencia sería que el formato fuese un enum en vez de un string para restringirlo según lo indicado en #2 , buen trabajo :+1:

2024-11-21 18:34 UTC, JJ commented
> Perdón por no aprobarlo antes, tras revisarlo yo lo veo bien. Una sugerencia sería que el formato fuese un enum en vez de un string para restringirlo según lo indicado en #2 , buen trabajo 👍

En revisiones no se prohibe hacer sugerencias, pero si formularlas así. Si las formulas así parece que la persona está obligada a hacerlo; sin embargo, si le preguntas si ha considerado esa opción simplemente verá esa opción como otra posibilidad, con la posibilidad de descartarla si ve que no añade más valor al cliente que lo que ya se ha hech.o. Por otro lado, también deben hacerse en la línea donde ocurran simplemente para reducir el trabajo por parte de esa persona.

2024-11-21 18:39 UTC, JJ requested changes
Por favor, cuando acabes sería conveniente que @blancagiron revisara también y aprobara en su caso.

2024-11-21 18:39 UTC, JJ commented on pkg/segurasenior/fuentes.go
> +const (
¿Qué valor añade esto al cliente? ¿En qué se va a usar en la lógica de negocio?

2024-11-21 18:39 UTC, JJ commented on pkg/segurasenior/fuentes.go
> +func (f Formato) String() string {
¿Y esto por qué forma parte del modelo?

2024-11-21 18:39 UTC, JJ commented on pkg/segurasenior/fuentes.go
> +type Formato int
¿Esto aporta valor al cliente?

2024-11-21 18:39 UTC, JJ commented on pkg/segurasenior/poblacion.go
> +	Tasa_natalidad      int
Aparte del hecho de que esto sea o no lo que la clienta necesita, ¿una tasa puede ser un entero?

2024-11-21 18:39 UTC, JJ commented on pkg/segurasenior/poblacion.go
> +func NewPoblacion(nom string, poblacion int, tasan int, tasae int, tasam int) (*Poblacion, error) {
¿Crees que aporta algún valor agrupar todo esto en un struct? ¿La "población" vas a generarla a partir de los valores de las variables? ¿Y de dónde sacas esos valores?
Por otro lado, trata de respetar las convenciones sobre nombre también en los argumentos.

2024-11-21 18:39 UTC, JJ commented on pkg/segurasenior/poblacion.go
> +	Nombre_pueblo       string
¿En Go que implica que un atributo comience por mayúscula o minúscula? ¿Es eso lo que quieres?

2024-11-21 18:39 UTC, JJ commented on pkg/segurasenior/poblacion.go
> +	return &Poblacion{
Modelar no es asignar nombres a las cosas, es ver cómo se puede representar mejor el problema. ¿Meter todo en un array es la mejor forma de manejar todo esto?

2024-11-21 18:39 UTC, JJ commented on pkg/segurasenior/reportaje.go
> +	Fuentes             []Fuente
Y esto ya lo hemos hablado.

2024-11-21 18:44 UTC, ChinChainis commented on pkg/segurasenior/fuentes.go
> +const (
Esto forma parte del enum para el tipo de formato, no entiendo este comentario.

2024-11-21 18:45 UTC, ChinChainis commented on pkg/segurasenior/fuentes.go
> +type Formato int
Dependiendo de un formato u otro se necesita un tipo de web scraping distinto solicitado por el cliente en #2 .

2024-11-21 18:49 UTC, JJ commented on pkg/segurasenior/fuentes.go
> +func (f Formato) String() string {
Lee arriba.

2024-11-21 18:50 UTC, ChinChainis commented on pkg/segurasenior/poblacion.go
> +	Tasa_natalidad      int
El cliente necesita esto, lo pide para poder filtrar la información, sí es cierto que debe emplearse un valor de números entero. https://github.com/blancagiron/SeguraSenior/pull/8/commits/6f809b4463e163dc73aa579fc5fc4a272977f45f

2024-11-21 18:58 UTC, ChinChainis commented on pkg/segurasenior/reportaje.go
> +	Fuentes             []Fuente
Para hacer un reportaje entendemos que tenemos las fuentes por un lado y la información de la población por otro, el conjunto de estos dos forma un reportaje y ahora no depende los datos de uno u otro.

2024-11-21 19:00 UTC, ChinChainis commented on pkg/segurasenior/fuentes.go
> +type Formato int
No aporta realmente al modelo del problema pero me han sugerido que usara un tipo enum para las extensiones para mayor comodidad y eso permite tenerlos asignados a enteros para fácil asignación.

2024-11-21 19:01 UTC, JJ commented on pkg/segurasenior/fuentes.go
> +type Formato int
Esto no tiene nada que ver con el enum.

2024-11-21 19:01 UTC, ChinChainis commented on pkg/segurasenior/fuentes.go
> +const (
Para aplicar una función de web scraping distinta según el formato.

2024-11-21 19:02 UTC, JJ commented on pkg/segurasenior/fuentes.go
> +const (
¿Sin este enum no puede distinguir entre los formatos?

2024-11-21 19:10 UTC, ChinChainis commented on pkg/segurasenior/fuentes.go
> +const (
Si solo se almacena un string de datos necesitaremos saber de dónde ha provenido la información, yo no digo que se necesite explícitamente el enum para hacer el web scraping, se necesita para categorizar a la hora de hacer web scraping con que estamos trabajando, antes lo tenía como un string pero con esto podemos implementar de forma más rápida y concisa los tipos de datos a analizar y solo esos.

2024-11-21 19:13 UTC, ChinChainis commented on pkg/segurasenior/fuentes.go
> +type Formato int
Lo necesitamos para asignar los valores del enum a números, se inicializa a int para luego asignar a cada número un valor específico que se puede leer como string, asignando posiciones y strings respectivamente. Todos los tutoriales de cómo hacer un tipo de dato enum lo recomiendan hacer de este método para que funciones de forma similar a sus contrapartes en otros lenguajes.

2024-11-21 19:18 UTC, ChinChainis commented on pkg/segurasenior/poblacion.go
> +func NewPoblacion(nom string, poblacion int, tasan int, tasae int, tasam int) (*Poblacion, error) {
Los valores los obtengo de haber analizado una fuente de información, una población de cierto nombre tiene número de habitantes total que se podría usar para comparar junto a las tasas el nivel de mortalidad o natalidad de un lugar específico, es una entidad necesaria para deducir luego la tendencia de esa población y añadirlo al reporte pedido.
Respecto al tema de los nombres el visual studio me daba error a la hora de ponerlos en minúscula pero debe ser por un plugin que no he controlado bien, lo arreglaré.

2024-11-21 19:29 UTC, JJ commented on pkg/segurasenior/fuentes.go
> +const (
Estás diciendo para qué lo necesitas tú. Yo te estoy preguntando para qué lo necesita el cliente, además desde el principio.

2024-11-21 19:33 UTC, JJ commented on pkg/segurasenior/fuentes.go
> +type Formato int
En general, si contestas a una pregunta con "lo necesito yo" o "lo necesitamos" en vez de "lo necesita el cliente", es que no estás aportando valor al cliente. En general, hacer un alias de un tipo aporta poquísimo o ningún valor al cliente y realmente muy poco al programador. Usando buenas prácticas en nombres de variables se puede conseguir lo mismo, y añadir tipos espurios que no tienen ninguna funcionalidad adicional solo aporta carga cognitiva a la persona que programa que tiene que buscar y retener cosas como que `Formato`  en realidad es un entero.
Por otro lado, cuando hago comentarios no es para que iniciemos una discusión sobre el tema. En general, es para que reflexiones y consideres alternativas a algo que es muy posible que no haya que hacer o hacer de otra forma. Enpecinarte en un review por justificar lo que has hecho y no admitir que hay alternativas que sirvan mejor a un cliente no parece que aporte ningún valor ni a mi ni a tu avance hacia la consecución del objetivo.

2024-11-21 19:34 UTC, JJ commented on pkg/segurasenior/poblacion.go
> +	Tasa_natalidad      int
Las tasas se cuentan sobre 1. Los porcentajes sobre 100. En cualquiera de los casos, hay infinitos valores entre 0 y 1. Te vuelvo a repetir, insistir en que una cosa está bien como está y no hay que considerar ninguna otra alternativa no parece que lleve a ningún lado, y desde luego no te acerca a la aprobación de este PR.

2024-11-21 19:35 UTC, JJ commented on pkg/segurasenior/poblacion.go
> +func NewPoblacion(nom string, poblacion int, tasan int, tasae int, tasam int) (*Poblacion, error) {
No, lo que tienes que hacer es un modelo. Esos valores se obtienen en algún lado y si tu modelo no incluye de dónde se obtienen, lo único que estás haciendo es darle nombre a las cosas. Para eso no hace falta ningún tipo de modelización.

2024-11-21 19:50 UTC, JJ requested changes
No creo que sea necesario insistir, pero cuando se hace un comentario es porque o bien donse se hace el comentario hay algo que no se entiende, que es inconsistente o simplemente que no se puede evaluar. En el 90% de los casos, hay que cambiar el código donde se ha hecho el comentario, porque *nunca hay una sola forma de hacer las cosas*. Si no te gusta lo que te pide que consideres la persona que te lo dice, es posible que haya  muchas otras formas. Pero el código siempre debe ser resultado *del equipo*, entendiendo como tal la persona que escribe el código y la persona que lo revisa y eventualmente lo acepta.

2024-11-21 19:50 UTC, JJ commented on pkg/segurasenior/tendencia.go
> +type Estadopoblacion int
¿Qué dicen las mejores prácticas de Go sobre este nombre? ¿Y sobre que los int tengan dos nombres diferentes dependiendo de en qué fichero estés?

2024-11-21 19:50 UTC, JJ commented on pkg/segurasenior/reportaje.go
> +	Fuentes             []Fuente
Estás en el issue #9, que habla de "descripción de un reportaje" y de "qué información requiere". Ese issue se refiere a #2, que habla del problema de consolidar datos de diferentes fuentes. ¿Estás incluyendo aquí en el código algo que ni se menciona ni aparentemente tiene nada que ver con ninguna de las dos cosas, y además en un format complicado de manejar desde la lógica de negocio?
En blame, aparece modificado por este commit: https://github.com/blancagiron/SeguraSenior/commit/8ad186e74622184ac8b96530c3e1ab9458515f66. En él has hecho dos cosas, sin seguir las buenas prácticas, que dicen que los commits deben ser atómicos. Si has quitado Retransmision, eso sería un commit. Cambiar nombres, sería otro.
Navegando por los commits, has insertado `Fuente` aquí: e9b0c92. En el mensaje de commit dice "fixes https://github.com/blancagiron/SeguraSenior/issues/9 añadidos nuevos tipos de datos importados". Ni explicas qué decisión te ha llevado a eso, ni parece que tenga nada que ver con el contenido del commit. ¿Tendencia y "Fuente" son datos importados?
En resumen: hay que seguir las buenas prácticas, pero sobre todo no obligar a la persona que revisa a mirar toda la historia de commit para hacerte entender por qué incluir algo que no parece que modele el problema que tiene la clienta no es una buena idea. No lo es primero porque no lo es, pero segundo y mucho más importante porque no has seguido las buenas prácticas exigibles a la hora de insertar ese código.

2024-11-21 21:20 UTC, ChinChainis commented on pkg/segurasenior/poblacion.go
> +	Nombre_pueblo       string
Las convenciones de golang dicen que las variables van en minúscula es cierto. https://github.com/blancagiron/SeguraSenior/pull/8/commits/3dc8d33f0754d41b7982f1f84af3d8646e70b65d

2024-11-21 21:38 UTC, ChinChainis commented on pkg/segurasenior/poblacion.go
> +	return &Poblacion{
Es mejor separar la validación de las tasas para saber cuál falla concretamente https://github.com/blancagiron/SeguraSenior/pull/8/commits/fb532dfa8b33db9ffb2a1aee5adf0b00ab1b0506

2024-11-22 12:22 UTC, ChinChainis commented on pkg/segurasenior/tendencia.go
> +type Estadopoblacion int
https://github.com/blancagiron/SeguraSenior/pull/8/commits/0b81875691a69a74543744c7041018c3f9930e56 he leído en el documento de desarrollo de Go que empieza por mayúscula y que cada uno define de forma independiente la posición del valor predeterminado, no están relacionados entre sí.

2024-11-22 16:08 UTC, ChinChainis commented
@blancagiron Si cuando puedas pudieras echarle un ojo, gracias.

2024-11-24 13:10 UTC, blancagiron commented on pkg/segurasenior/poblacion.go
> +	tasa_mortalidad     float32
Esta entidad en general me parece correcta ¿has pensado en la utilidad de añadir datos como los habitantes menores de cierta edad, los habitantes en edad adulta o los habitantes mayores, además de la población total?

2024-11-24 13:15 UTC, blancagiron commented on pkg/segurasenior/tendencia.go
> +	nombre_pueblo_tendencia string
¿Has considerado que el atributo nombre_pueblo_tendencia podría estar ya representado por el atributo poblacion.nombre_pueblo dentro de Tendencia? ¿Has considerado si la tendencia en vez de una entidad independiente podría ser calculada directamente a partir de los datos de la población aunque sea en objetivos futuros?

2024-11-24 13:17 UTC, blancagiron commented on pkg/segurasenior/reportaje.go
> +package segurasenior
¿Crees que el concepto de un Reportaje como entidad es fundamental para modelar el flujo de trabajo de #2 ?
Si el "reportaje" solo es una salida o producto final del análisis, ¿es necesario representarlo como una entidad dentro del modelo ?

2024-11-24 13:19 UTC, blancagiron reviewed
He escrito una serie de aspectos a tener en cuenta por si quieres revisarlos, es un buen trabajo. Por otro lado, ¿Has considerado cómo vas a representar las fuentes de datos en el modelo? Si los datos provienen de múltiples fuentes , ¿cómo manejarías esta dispersión de formatos y referencias sin un modelo específico para las fuentes?

2024-11-24 17:56 UTC, ChinChainis commented on pkg/segurasenior/poblacion.go
> +	tasa_mortalidad     float32
https://github.com/blancagiron/SeguraSenior/pull/8/commits/12afc8e810a35b6818ca57d98d6abd270fa84b1c

2024-11-24 17:58 UTC, ChinChainis commented on pkg/segurasenior/tendencia.go
> +	nombre_pueblo_tendencia string
https://github.com/blancagiron/SeguraSenior/pull/8/commits/65b7229bd350b115b19dff62080515a3fbaaff4b

2024-11-24 18:03 UTC, ChinChainis commented on pkg/segurasenior/reportaje.go
> +package segurasenior
https://github.com/blancagiron/SeguraSenior/pull/8/commits/2e44cdc926445968aa9b6120510cfa787f885529 para extraer la información de una fuente. almacenar los datos y estudiar una tendencia de una población necesitaríamos presentarlos en un dato para trabajarlo.

2024-11-25 17:06 UTC, blancagiron approved these changes
Los cambios me parecen adecuados, veo el modelo bien :+1:

2024-11-25 18:02 UTC, ChinChainis commented
@JJ si pudieras revisarlo cuando puedas por favor.

2024-11-25 18:39 UTC, JJ requested changes
No entiendo muy bien por qué volvéis a enviar código que ya se comentó que deberíais considerar eliminarlo. Tratar de imponer una solución al resto del equipo no suele ser una buena estrategia de trabajo en equipo, y especialmente no es una que permita avanzar hacia la aprobación de este objetivo, donde una de las cosas que se persiguen es que las personas que participan entiendan cuál es la dinámica y la utilidad de un pull request, y especialmente cómo código aportado por personas del equipo puede (y debe) ser utilizado más adelante.
Sé que hasta ahora todas las asignaturas de la carrera han ido enfocadas a hacer una cosa de una manera determinada, "la que diga el profe". El mundo real no es así. No hay nunca una sola solución, y la solución buena es la que sigue el proceso: se piensa a partir de los deseos del cliente, trata de aportar valor al cliente, **y si alguno de los miembros del equipo pone en duda ese valor aportado al cliente** se reconsidera y en su caso se rechaza. No entenderlo así es no entender el proceso de revisión en desarrollo ágil. Y desde luego, volver a enviar soluciones que ya se ha pedido que se reconsideren no parece la mejor forma de emplear el tiempo para ninguno de nosotros.

2024-11-25 18:39 UTC, JJ commented on pkg/segurasenior/fuente.go
> +type FormatoFuente string
Creo que ya hemos tenido esta discusión, pero permíteme que insista. ¿Qué problema resuelve esta creación de un alias de tipo? ¿Qué valor aporta al cliente?

2024-11-25 18:39 UTC, JJ commented on pkg/segurasenior/fuente.go
> +	HTML  FormatoFuente = "html"
Igual hemos tenido ya esta discusión, pero ¿qué valor aporta esto al cliente? ¿De qué forma es parte de un producto mínimo? ¿Por qué es parte del modelo del problema? ¿Para qué va a ser esto útil en la lógica de negocio?

2024-11-25 18:39 UTC, JJ commented on pkg/segurasenior/fuente.go
> +	Formato_fuente          FormatoFuente
@blancagiron ¿hay algo en la lógica de negocio que necesite el formato de la fuente? Si no es así, ¿por qué lo has aprobado?

2024-11-25 22:15 UTC, blancagiron commented on pkg/segurasenior/fuente.go
> +	Formato_fuente          FormatoFuente
Aprobé el campo `Formato_fuente` porque pensé que era importante incluirlo, ya que #2  menciona explícitamente que los datos están dispersos en múltiples formatos (PDF, Excel, HTML). Creía que reflejar este detalle en el modelo era relevante para representar la problemática descrita.  

Sin embargo, tras pensarlo mejor:  

- No hay lógica de negocio asociada al formato actualmente. Aunque la HU menciona los formatos, no hay una funcionalidad clara en este momento que dependa de este atributo para resolver el problema principal de Raquel, que es consolidar y analizar los datos.  

- Este dato podría gestionarse en otro nivel  y no necesariamente en el modelo del problema, ya que lo que importa es tener la información procesada y lista para analizar.  

Ahora entiendo que incluir el formato en el modelo principal puede no ser necesario.

2024-11-26 16:56 UTC, ChinChainis commented on pkg/segurasenior/fuente.go
> +	HTML  FormatoFuente = "html"
https://github.com/blancagiron/SeguraSenior/pull/8/commits/75ac4992f9f7d6e6fb0c29268e87405dbcc3e071

2024-11-26 16:57 UTC, ChinChainis commented on pkg/segurasenior/fuente.go
> +type FormatoFuente string
https://github.com/blancagiron/SeguraSenior/pull/8/commits/75ac4992f9f7d6e6fb0c29268e87405dbcc3e071

2024-11-27 07:49 UTC, JJ commented on pkg/segurasenior/fuente.go
> +	Formato_fuente          FormatoFuente
Todo código que se convierte en deuda técnica se justifica con "Pensé que era necesario incluirlo"

2024-11-27 07:55 UTC, JJ reviewed
De los [errores frecuentes](https://github.com/JJ/IV-/blob/master/errores/objetivo-2.md#sobre-los-milestones)

> Es muy difícil que un modelo esté completo sin una entidad, que almacene los objetos valor, incluya (más adelante) la lógica de negocio para crearlos, y los relaciones unos con otros. Si no hay una entidad, o si no sabes si hay una entidad o no, es que no está correcto.

Y vuelvo a insistir en lo mismo. En un plazo muy corto @blancagiron va a tener que trabajar con esto. Si apruebas algo que necesite *mucho* trabajo adicional, puedes tener un problema.

2024-11-27 07:55 UTC, JJ commented on pkg/segurasenior/poblacion.go
> +type Poblacion struct {
Los nombres deben reflejar el contenido de los mismos. ¿Te parece que "Poblacion" refleja realmente el contenido de la variable?

2024-11-27 07:55 UTC, JJ commented on pkg/segurasenior/tendencia.go
> +	Nombre_pueblo_tendencia string
Esta tendencia, ¿sobre qué se va a medir? Si es sobre instancias de `Pueblo`, ¿dónde está la *entidad* que maneja esas instancias?

2024-11-27 11:47 UTC, ChinChainis commented on pkg/segurasenior/poblacion.go
> +type Poblacion struct {
https://github.com/blancagiron/SeguraSenior/pull/8/commits/ca1e1ad0ec383ca24604200e9791fb4ff5cfff7f

2024-11-27 11:47 UTC, ChinChainis commented on pkg/segurasenior/tendencia.go
> +	Nombre_pueblo_tendencia string
https://github.com/blancagiron/SeguraSenior/pull/8/commits/145cf5b72b5e15465f77e5d70bfad18de6a7cd4a

2024-11-28 07:41 UTC, blancagiron commented on pkg/segurasenior/fuente.go
> +	Nombre_poblacion_fuente string
¿Has pensado si es necesario `Nombre_fuente` , para una fuente no bastaría el nombre de la población y `Direccion`?

2024-11-28 08:03 UTC, ChinChainis commented on pkg/segurasenior/fuente.go
> +	Nombre_poblacion_fuente string
https://github.com/blancagiron/SeguraSenior/pull/8/commits/efc08c063087b6cc5c39c52a75694f1cd44b537d

2024-11-28 08:19 UTC, blancagiron reviewed
Aquí te he dejado algunas sugerencias

2024-11-28 08:19 UTC, blancagiron commented on pkg/segurasenior/demografia.go
> +}
Según veo representaría el registro demográfico de varios pueblos al tener `Estadisticas_poblacion` y `Fuentes`como array ¿no has considerado que si quieras mantener este enfoque `Tendencias_poblacion` tendría que ser un array también? Por otro lado, ¿Te has planteado que en vez de ser el registro demográfico de varias poblaciones represente el registro de una sola población? ¿Crees que en este caso es necesario que `Tendencia`y `Fuente`tengan también como atributo el nombre de la población que ya está incluido en `Datos_poblacion` ? ¿Has considerado si con este nuevo posible enfoque un tipo de dato sea un array de `Registro_demografico`?

2024-11-28 08:19 UTC, blancagiron commented on pkg/segurasenior/tendencia.go
> +	if estado != Decreciente && estado != Creciente {
¿Has considerado si al seguir el nuevo enfoque es necesario mantener el nombre del pueblo? ¿Has pensado que en `Registro_demografico` ya queda asociado el pueblo y sus datos con la fuente y la tendencia? Así mismo ¿Te has planteado la posibilidad de que en vez de `Tendencia` se use simplemente `Estado`como atributo en `Registro_demografico`?

2024-11-28 12:03 UTC, ChinChainis commented on pkg/segurasenior/tendencia.go
> +	if estado != Decreciente && estado != Creciente {
> ¿Has considerado que esta comprobación puede no ser necesaria ya que estás haciendo una validación por tipos?

https://github.com/blancagiron/SeguraSenior/pull/8/commits/53d1aa26f1c146a060400fec40797efad64d7c85

2024-11-28 12:05 UTC, ChinChainis commented on pkg/segurasenior/tendencia.go
> +	if estado != Decreciente && estado != Creciente {
> ¿Has considerado si al seguir el nuevo enfoque es necesario mantener el nombre del pueblo? ¿Has pensado que en `Registro_demografico` ya queda asociado el pueblo y sus datos con la fuente y la tendencia? Así mismo ¿Te has planteado la posibilidad de que en vez de `Tendencia` se use simplemente `Estado`como atributo en `Registro_demografico`?

https://github.com/blancagiron/SeguraSenior/pull/8/commits/e64875d6450de2f6387a71a204575c68456cb2d3
https://github.com/blancagiron/SeguraSenior/pull/8/commits/9ecac2963f5d59ca40cbff1001abed63bba3bca5
También he eliminado el uso de fuentes.go
https://github.com/blancagiron/SeguraSenior/pull/8/commits/5af6951bb0a26d60a702ef97d912c5110d82cadb
https://github.com/blancagiron/SeguraSenior/pull/8/commits/9052b77a3fe716224427a2af0dd84e865deb8143

2024-11-28 12:13 UTC, blancagiron commented on pkg/segurasenior/demografia.go
> +func (e Estado) String() string {
¿Has considerado que una funcion para pasar a string puede no ser parte del modelo del problema?

2024-11-28 12:15 UTC, ChinChainis commented on pkg/segurasenior/demografia.go
> +func (e Estado) String() string {
https://github.com/blancagiron/SeguraSenior/pull/8/commits/36eb4098a68f440833983eafc1a33601b03c14b0

2024-11-28 12:21 UTC, ChinChainis commented on pkg/segurasenior/demografia.go
> +}
Comentamos en persona que un registro solo debería tener una instancia de datos y una de tendencia para que no haya conflictos entre información y así cada registro se refiere a una única población concreta. Fuentes sí lo veo como un tipo de dato que puede ir en array

2024-11-28 12:54 UTC, blancagiron approved these changes
Este enfoque me parece más adecuado. A mí me parece bien :+1:

2024-11-28 12:58 UTC, ChinChainis commented on pkg/segurasenior/demografia.go
> +}
Respecto a lo de representar Tendencias_poblacion como un array creo que puede dar lugar a que un registro no esté centralizado y pueda tener datos conflictivos, una población no debería poder ser creciente y decreciente a la vez en una misma medición, con este enfoque que te he enviado centraliza los datos de un registro a una sola población por si te parece mejor.

2024-11-28 19:16 UTC, JJ requested changes
Creo que la simplificación ha mejorado bastante, aunque sigues poniendo algunas cosas que ya se dijo que posiblemente no eran necesarias (como las fuentes), cambiándolas de nombre, pero ahora hay otras prioridades; te agradecería que le dieras un (posiblemente último) vistazo y revisión. Recuerda que @blancagiron debe revisarlo antes de que me solicitéis de nuevo revisión.

2024-11-28 19:16 UTC, JJ commented on pkg/segurasenior/demografia.go
> +type Estado int
Estoy viendo [aquí](https://gobyexample.com/enums) que efectivamente esta es la forma de hacer una especie de Enum en go y que esto *sí proporciona seguridad de tipo*. Estaba yo equivocado pensando que podría usarse cualquier entero aquí.
Pero *de verdad* lo mejor habría sido que buscárais este recurso, donde dice:

> If we have a value of type int, we cannot pass it to transition - the compiler will complain about type mismatch. This provides some degree of compile-time type safety for enums.

Nada da más satisfacción a un estudiante que probar que un profesor está equivocado. Si hubiérais buscado vuestro propio código en los manuales (GoByExample es excelente)  o siquiera pedido a CoPilot que os explique por qué hace una cosa de una forma, habríais tenido esa satisfacción en vez de una bastante inferior que es la de que el profesor os pida disculpas.

2024-11-28 19:16 UTC, JJ commented on pkg/segurasenior/demografia.go
> +type Registros_demografia []Registro_demografico
@blancagiron ¿crees que esto aporta valor al cliente tal como está? ¿Hay otras alternativas para hacer lo mismo?
En cuanto a usar un array, ¿es la mejor forma de hacerlo? Si quieres el Registro demográfico de una población específica, ¿qué tienes que hacer para recuperarlo?

2024-11-28 19:16 UTC, JJ commented on pkg/segurasenior/demografia.go
> +	Decreciente Estado = iota
¿El estado eventualmente va a imprimirse o incluirse en un informe? Si es así, usar un `int` es la mejor forma de hacerlo?

2024-11-28 19:16 UTC, JJ commented on pkg/segurasenior/poblacion.go
> +func NewPoblacion(nom string, poblacion int, poblacionjoven int, poblacionmedia int, poblacionmayor int, tasan float64, tasae float64, tasam float64) (*Datos_poblacion, error) {
¿Qué hemos dicho sobre los nombres de las variables?
En código limpio (y en un modelo) el nombre de una variable debe corresponder al "lenguaje ubicuo" que se establece a través de diseño dirigido por dominio. Por eso hay que contemplar especialmente los nombres de las variables.
Y también deben seguir las mejores prácticas. `poblacionjoven` ¿las sigue?

2024-11-28 19:16 UTC, JJ commented on pkg/segurasenior/poblacion.go
> +	if (poblacionjoven <= poblacion) || (poblacionjoven < 0) {
No me acaban de gustar este código de validación por varias razones.
1. No corresponden estrictamente al modelo.
2. Estás testeando cosas (como que sea menor que 0 o no) que podías evitar usando un tipo más adecuado.
3. Finalmente, código que no se testea es código erróneo. ¿Estás seguro que este código comprueba lo que crees que comprueba? ¿Qué pasa si `poblacionjoven` = 33 y `poblacion` = 44? ¿Daría error o no?

2024-11-28 19:16 UTC, JJ commented on pkg/segurasenior/poblacion.go
> +	if (tasan < 0.0) || (tasan > 1000.0) {
¿Las tasas pueden valer de 0 a 1000? ¿Qué tipo de tasa es esa? Una vez más, el modelo debe establecer un lenguaje ubicuo que llame a cada cosa de la misma manera que lo haría el cliente. No hay límite en el número de caracteres que puede tener una variable, así que ¿por qué abreviar?

2024-11-28 21:34 UTC, blancagiron commented on pkg/segurasenior/demografia.go
> +type Registros_demografia []Registro_demografico
Es cierto que el uso de un array no es el mejor. @ChinChainis ¿has pensado en explorar otras estructuras que pueden ser más eficientes cómo los mapas?

2024-11-29 11:52 UTC, ChinChainis commented on pkg/segurasenior/poblacion.go
> +	if (poblacionjoven <= poblacion) || (poblacionjoven < 0) {
Es verdad, no es relevante para esta fase y con un uint32 podríamos ahorrar un montón de código https://github.com/blancagiron/SeguraSenior/pull/8/commits/ba49d3be3802ed2896c1d2102f9d370c38efb42c

2024-11-29 12:15 UTC, ChinChainis commented on pkg/segurasenior/demografia.go
> +	Decreciente Estado = iota
https://github.com/blancagiron/SeguraSenior/pull/8/commits/02d51c8a9ac9010a41f630c963690e92d028fae3 es mejor en formato string.

2024-11-29 12:52 UTC, ChinChainis commented on pkg/segurasenior/poblacion.go
> +	if (tasan < 0.0) || (tasan > 1000.0) {
https://github.com/blancagiron/SeguraSenior/pull/8/commits/25fcc1545f456930e76240a54af6b50311b20eca

2024-11-29 12:56 UTC, ChinChainis commented on pkg/segurasenior/demografia.go
> +type Registros_demografia []Registro_demografico
https://github.com/blancagiron/SeguraSenior/pull/8/commits/ad7d2343d4929ca8b7d2b333552f91fb5fdca650 puede que te sirva más una que esté mapeada a strings.

2024-11-29 13:17 UTC, blancagiron commented on pkg/segurasenior/demografia.go
> +	Estadisticas_poblacion Datos_poblacion
Según he podido ver en Reddit y en recursos como [aquí](https://google.github.io/styleguide/go/guide#mixed-caps) , en Go se suele usar más Camel case que Snake case ¿has considerado usar esta nomenclatura?

2024-11-29 13:18 UTC, blancagiron approved these changes
El modelado me parece correcto, ya quedaría que considerases si esa es la nomenclatura que quieres usar o si quieres cambiarla. Por mí todo bien :+1:

2024-11-29 13:30 UTC, ChinChainis commented on pkg/segurasenior/demografia.go
> +	Estadisticas_poblacion Datos_poblacion
https://github.com/blancagiron/SeguraSenior/pull/8/commits/1d80dc927f0efcde3637c1c3167622ede8060d14

2024-11-29 13:30 UTC, ChinChainis commented on pkg/segurasenior/poblacion.go
> +		Nombre_pueblo:       nom,
https://github.com/blancagiron/SeguraSenior/pull/8/commits/7e47f4bd5048c80cc50e51246599bf8a8946f8fd

2024-12-02 07:30 UTC, JJ requested changes
Has hecho un buen esfuerzo para simplificar y en ese sentido hamejorado mucho; sin embargo, tanto tú como @blancagiron debeis reflexionar sobre cómo se puede usar esto como base para la lógica de negocio.

2024-12-02 07:30 UTC, JJ commented on pkg/segurasenior/demografia.go
> +func NewRegistro(poblacion DatosPoblacion, tendencia Estado) (*RegistroDemografico, error) {
El nombre de las cosas es importante. Una `poblacion` no es una instancia de `DatosPoblacion`. Y una `tendencia` no es un `Estado'. Esta disonancia cognitiva entre el nombre de los instancias y el tipo al que pertenecen hace que sea más complicado entender el código. Y una vez más, no entiendo el afán por escribir las cosas de forma abreviada que hace el código más confuso.

2024-12-02 07:30 UTC, JJ commented on pkg/segurasenior/poblacion.go
> +func NewPoblacion(nom string, poblacion uint32, poblacionMenor18 uint32, poblacionEntre18Y64 uint32, poblacionMayor64 uint32,
¿`NewPoblacion` no sería un constructor para una clase `Poblacion`?
Por otro lado, ¿`nom` sigue las buenas prácticas de código limpio y del lenguaje?

2024-12-02 07:30 UTC, JJ commented on pkg/segurasenior/demografia.go
> +type Registros_demografia map[string][]RegistroDemografico
¿Qué es la clave aquí? Si es el nombre del pueblo, ¿te parece que usarlo como clave y también como parte del objeto cree una posible disonancia que rompa el principio de SSOT (única fuente de verdad?
Por otro lado, si quieres instanciar un `RegistroDemografico`, @blancagiron ¿de donde sacarías las instancias de `DatosPoblacion`?

2024-12-02 07:30 UTC, JJ commented on pkg/segurasenior/demografia.go
> +	TendenciasPoblacion   Estado
¿No dice nada la historia de usuario sobre "reportajes"? ¿Los reportajes no tienen fecha? ¿Los datos no tienen fecha? ¿Esto es una cantidad absoluta? @blancagiron ¿vas a poder trabajar con esto en la lógica de negocio?

2024-12-02 07:30 UTC, JJ commented on pkg/segurasenior/demografia.go
¿Las buenas prácticas en go dicen algo sobre que un nombre de fichero aloje un objeto que se llame de otra forma?

2024-12-02 16:56 UTC, ChinChainis commented on pkg/segurasenior/demografia.go
https://github.com/blancagiron/SeguraSenior/pull/8/commits/3e4cb82fe6187cc0100ce8584f88ed74ab462926
https://github.com/blancagiron/SeguraSenior/pull/8/commits/df1cc382917115a0abd4891c097e815d498f12f1

2024-12-02 16:56 UTC, ChinChainis commented on pkg/segurasenior/poblacion.go
> +func NewPoblacion(nom string, poblacion uint32, poblacionMenor18 uint32, poblacionEntre18Y64 uint32, poblacionMayor64 uint32,
https://github.com/blancagiron/SeguraSenior/pull/8/commits/64ba69d5a97597e8b0f14bf310b47acc81dc824d

2024-12-02 16:57 UTC, ChinChainis commented on pkg/segurasenior/demografia.go
> +func NewRegistro(poblacion DatosPoblacion, tendencia Estado) (*RegistroDemografico, error) {
https://github.com/blancagiron/SeguraSenior/pull/8/commits/60347cfac6900a10f4ede7b3e6608cc2814d40cc
https://github.com/blancagiron/SeguraSenior/pull/8/commits/b1d08ff5f3abd8c7dc554faab799d016d8d1a0b0

2024-12-04 20:08 UTC, blancagiron commented on pkg/segurasenior/demografia.go
> +type Registros_demografia map[string][]RegistroDemografico
Es verdad que el nombre del pueblo como clave puede romper ese principio ya que este dato también está presente en `DatosPoblacion`. ¿Has pensado @ChinChainis en eliminar el campo `NombrePoblacion` en `DatosPoblacion` para evitar la duplicación de datos o en usar otro atributo como clave? ¿Tienes otras ideas? Por otro lado, es cierto que en el modelo actual no hay una fuente clara para obtener instancias de `DatosPoblacion` y deja abierta la pregunta sobre de dónde vienen esos datos. ¿Has considerado @ChinChainis en usar una entidad para generar y almacenar `DatosPoblacion`y luego usar esta información para crear registros demográficos? ¿Se te ocurre otra manera de instanciar los datos?

2024-12-04 20:12 UTC, blancagiron commented on pkg/segurasenior/registrodemografico.go
> +	EstadoDeLaPoblacion   EstadoPoblacion
aquí no crees que el estado de la población es algo que se debería de calcular en base a `EstadisticasPoblacion`en vez de que sea algo que introduces como parámetro?

2024-12-10 22:18 UTC, ChinChainis commented on pkg/segurasenior/demografia.go
> +	TendenciasPoblacion   Estado
https://github.com/blancagiron/SeguraSenior/pull/8/commits/8e35d49787c8c600f46b82f47ef9ad113d5930c0
He añadido un campo para fecha que engloba solo día, mes y año

2024-12-10 22:19 UTC, ChinChainis commented on pkg/segurasenior/demografia.go
> +type Registros_demografia map[string][]RegistroDemografico
https://github.com/blancagiron/SeguraSenior/pull/8/commits/3e368514e445cd10ded33e8e53f22dee78dfe265
https://github.com/blancagiron/SeguraSenior/pull/8/commits/cfd21790643a0b34228227abecb9c2cfed8bdf36
He incluido un array de datos tipo datospoblacion con un campo con clave comprendida por el nombre del pueblo y la fecha evitando que pueda haber 2 con el mismo identificador, si le pudieras echar un vistazo a ver qué te parece

2024-12-10 22:20 UTC, ChinChainis commented on pkg/segurasenior/registrodemografico.go
> +	EstadoDeLaPoblacion   EstadoPoblacion
Creo que sería meter demasiada lógica para ser un modelo, sin embargo puedo poner un array de datos para poder almacenar distintas instancias de datos de población según un mismo pueblo o fecha
https://github.com/blancagiron/SeguraSenior/pull/8/commits/cfd21790643a0b34228227abecb9c2cfed8bdf36

2024-12-11 19:38 UTC, blancagiron commented on pkg/segurasenior/datospoblacion.go
> +type DatosAlmacenadosDePoblaciones map[IdentificadorDatos][]DatosPoblacion
¿Has considerado que `DatosPoblacion` ya contiene un `IdentificadorDatos`, pero también defines un mapa llamado `DatosAlmacenadosDePoblaciones` que usa `IdentificadorDatos` como clave?
Tal vez esta duplicidad puede llevar a redundancia

2024-12-11 19:43 UTC, blancagiron commented on pkg/segurasenior/datospoblacion.go
> +func NewDatosPoblacion(nombrefechadatos IdentificadorDatos, poblacion uint32, poblacionMenor18 uint32, poblacionEntre18Y64 uint32, poblacionMayor64 uint32,
aquí igual, `NombreFechaDatos` incluye información que también es clave en el mapa `DatosAlmacenadosDePoblaciones` ¿has considerado la posibilidad de eliminarlo ?

2024-12-11 19:46 UTC, blancagiron commented on pkg/segurasenior/registrodemografico.go
> +	EstadisticasPoblacion DatosPoblacion
Aquí considero que la estructura parece diseñada para contener una única entrada de población `EstadisticasPoblacion`, pero el tipo `RegistrosDemografia` es un mapa que apunta a múltiples `RegistroDemografico`. ¿Has pensado en la posibilidad de que `EstadisticasPoblacion` sea un mapa?

2024-12-11 19:53 UTC, blancagiron commented on pkg/segurasenior/registrodemografico.go
> +type RegistrosDemografia map[string][]RegistroDemografico
¿Has considerado que `RegistrosDemografia` y `DatosAlmacenadosDePoblaciones` puedan no ser necesarios? Cómo he planteado antes, ¿has pensado en que `EstadisticasPoblacion` sea un mapa cuya clave puede ser `IdentificadorDatos` o tal vez `FechaObtencionDatos`?  ¿has considerado si no incluir el nombre de la población en las claves del mapa podría tener sentido si cada instancia de `RegistroDemografico` está diseñada para manejar una única población ? Mientras que incluir el nombre de la poblacion como parte de la clave puede tener más sentido si lo que queremos es manejar varias poblaciones dentro de un solo registro.

2024-12-11 21:55 UTC, ChinChainis commented on pkg/segurasenior/registrodemografico.go
> +type RegistrosDemografia map[string][]RegistroDemografico
https://github.com/blancagiron/SeguraSenior/pull/8/commits/b0a313829b54f43cc0afe1f5c327c84499571415

2024-12-11 21:56 UTC, ChinChainis commented on pkg/segurasenior/datospoblacion.go
> +type DatosAlmacenadosDePoblaciones map[IdentificadorDatos][]DatosPoblacion
https://github.com/blancagiron/SeguraSenior/pull/8/commits/51b645ec1d37d15d8691674d1353194e7652cb07

2024-12-11 21:56 UTC, ChinChainis commented on pkg/segurasenior/datospoblacion.go
> +func NewDatosPoblacion(nombrefechadatos IdentificadorDatos, poblacion uint32, poblacionMenor18 uint32, poblacionEntre18Y64 uint32, poblacionMayor64 uint32,
https://github.com/blancagiron/SeguraSenior/pull/8/commits/51b645ec1d37d15d8691674d1353194e7652cb07

2024-12-11 21:58 UTC, ChinChainis commented on pkg/segurasenior/registrodemografico.go
> +	EstadisticasPoblacion DatosPoblacion
https://github.com/blancagiron/SeguraSenior/pull/8/commits/4752b9fdcbe4a0dfaad506e3dfe5a4c2466e8cb3

2024-12-11 21:58 UTC, ChinChainis commented on pkg/segurasenior/datospoblacion.go
> +type DatosAlmacenadosDePoblaciones map[IdentificadorDatos][]DatosPoblacion
https://github.com/blancagiron/SeguraSenior/pull/8/commits/621d9d4ccd198742992dd753059378a49b18a1fc

2024-12-12 10:27 UTC, blancagiron commented on pkg/segurasenior/registrodemografico.go
> +type FechaObtencionDeDatos struct {
¿Has considerado la posibilidad de que `FechaObtencionDatos`e `IdentificadorDatos` estén en `datospoblacion` y así este fichero contenga los tipos y funciones relacionadas con los datos de la población?

2024-12-12 10:30 UTC, blancagiron commented on pkg/segurasenior/registrodemografico.go
> +	if len(datosPoblacion) == 0 {
¿Has considerado iterar sobre el mapa para asegurar que los elementos son válidos antes de crear el objeto? Creo que esto te puede permitir, por ejemplo, verificar la validez de  las fechas u otra validación que haya que aplicar

2024-12-12 11:36 UTC, ChinChainis commented on pkg/segurasenior/registrodemografico.go
> +}
https://github.com/blancagiron/SeguraSenior/pull/8/commits/109770e7dbdba485159c204e5bc31f5b7232d16e

2024-12-12 11:37 UTC, ChinChainis commented on pkg/segurasenior/registrodemografico.go
> +	if len(datosPoblacion) == 0 {
https://github.com/blancagiron/SeguraSenior/pull/8/commits/a29c66fdaa6cad29c6cea376e0de229e774cc057

2024-12-12 11:37 UTC, ChinChainis commented on pkg/segurasenior/registrodemografico.go
> +type FechaObtencionDeDatos struct {
https://github.com/blancagiron/SeguraSenior/pull/8

2024-12-12 11:38 UTC, ChinChainis commented on pkg/segurasenior/registrodemografico.go
> +type FechaObtencionDeDatos struct {
https://github.com/blancagiron/SeguraSenior/pull/8/commits/8bbd17f623c18d6713ef1e119a2bdee898d06caf

2024-12-12 18:06 UTC, blancagiron approved these changes
Tras ver las modificaciones que has realizado me parece un buen modelo

2024-12-13 16:18 UTC, JJ approved these changes
:+1:

2024-12-13 16:23 UTC, JJ requested changes
Las funciones no son *nunca* parte del modelo, ni si se usan para validar.

2024-12-13 16:23 UTC, JJ commented on pkg/segurasenior/registrodemografico.go
> +func daysIn(mes time.Month, anio uint16) int {
¿Esto es parte de un modelo?

2024-12-13 16:37 UTC, ChinChainis commented on pkg/segurasenior/registrodemografico.go
> +func daysIn(mes time.Month, anio uint16) int {
https://github.com/blancagiron/SeguraSenior/pull/8/commits/595aae044eb0c8ed8226e6eda2db635ea0aa4d54 era para asegurarse que la lógica del programa no permitiera que meses como febrero tuvieran más de 29 días pero entiendo que no es la información que toca analizar

2024-12-13 19:41 UTC, JJ approved these changes
:+1:

2024-12-13 19:48 UTC, blancagiron commented on pkg/segurasenior/registrodemografico.go
> +	}
Si bien las funciones no forman parte ¿has considerado validar de alguna otra manera la fecha?

2024-12-13 19:52 UTC, merged